### ISSUE TITLE
buffer_overflow_exception when configuring a repository in opensearch cluster with splitted roles

### ISSUE THREAD

**Issue by maxpschonder** [Aiven-Open/encrypted-repository-opensearch#61]
Hey folks,

I'm facing an issue when I try to create a repository in an OpenSearch cluster with separate manager nodes without the `data` role assigned to the managers, I get the following error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "buffer_overflow_exception",
        "reason" : "buffer_overflow_exception: null"
      }
    ],
    "type" : "repository_verification_exception",
    "reason" : "[test] path [encryptedrepo-test] is not accessible on cluster-manager node",
    "caused_by" : {
      "type" : "repository_exception",
      "reason" : "[test] cannot create blob store",
      "caused_by" : {
        "type" : "execution_exception",
        "reason" : "execution_exception: java.nio.BufferOverflowException",
        "caused_by" : {
          "type" : "buffer_overflow_exception",
          "reason" : "buffer_overflow_exception: null"
        }
      }
    }
  },
  "status" : 500
  ```

I tried it with a cluster in a docker compose stack and it works, when all nodes in the stack have the `data` role assigned. Do you have any advice?

Thanks in advance,

Max

**Comment by ndejesus** [comment]
Hi,

I have the same issue, when i try to create repository, i have this BufferOverflowException error coming.
We also have splitted roles for our servers.
However, i try to reproduce it on docker and it works, even with splitted roles.

@maxpschonder: Could you share your docker compose file if you were able to reproduce?

**Comment by willyborankin** [comment]
Hmm was it due  to the sec plugin enabled?
