### ISSUE TITLE
Searchable snapshots with encrypted repository

### ISSUE THREAD

**Issue by acidul** [Aiven-Open/encrypted-repository-opensearch#68]
Hi there, 
[searchable snapshot](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/) is a great feature in order to read data from a snapshot repository at search time...

Could it be compatible with encrypted repository?

**Comment by willyborankin** [comment]
Hi there, so far no. But we are working on it

**Comment by acidul** [comment]
This is very good news, thank you.
Will it be available in version 2.8?

**Comment by willyborankin** [comment]
Well I'm not sure. The problem is that the OpenSearch team started to work on the encryption plugin as well, but it looks like the work is stuck. So now we are thinking does it make sense to continue with this plugin or wait for the OpenSearch team.

**Comment by acidul** [comment]
OK, 
I will follow this point from opensearch side and here 
thanks a lot

**Comment by willyborankin** [comment]
Maybe something will appear

**Comment by acidul** [comment]
> Maybe something will appear

Hello, could you precise, please ?
